### ISSUE TITLE
Add section with members' Twitter feeds 

### ISSUE THREAD

**Issue by gchrupala** [tcsai/tcsai.github.io#3]

**Comment by cmry** [comment]
Would you prefer to have one mixed feed or a feed per person?

**Comment by gchrupala** [comment]
No strong preference, either could work.

**Comment by cmry** [comment]
Minimal effort version included in 350a68d09bd6149c6a752c466ba9ddab8ac37557. Would be most convenient to loop through nickname file in the `_yml` and generate query this way. Will fix this soon.

**Comment by cmry** [comment]
Stacking within an `href` seems undoable with liquid. Just gonna leave it at this and manually add twitter names for now. Also included our own twitter so page seems fuller at some point (aaf04da20a2c4ba6445281feee0e20272f53448b).
